import json
from datetime import datetime
from bot.journal import TradeJournal
from bot.models import ModelClient
from bot.errors import ModelError, JournalError

def compute_pnl_and_winrate(trades):
    """
    Compute P&L and win-rate from a list of trades.
    Assumes trades are sorted by timestamp and we only have long positions.
    Matches each BUY with the next SELL for the same symbol.
    :param trades: list of tuples (id, timestamp, symbol, action, qty, price, reasoning)
    :return: dict with total_pnl, win_rate, num_trades, num_winning, num_losing
    """
    # Group trades by symbol
    trades_by_symbol = {}
    for trade in trades:
        symbol = trade[2]
        trades_by_symbol.setdefault(symbol, []).append(trade)
    
    total_pnl = 0.0
    winning_trades = 0
    losing_trades = 0
    round_trips = 0
    
    for symbol, symbol_trades in trades_by_symbol.items():
        # Sort by timestamp
        symbol_trades.sort(key=lambda x: x[1])
        # We'll use a queue for buys
        buy_queue = []  # each element: (qty, price)
        for trade in symbol_trades:
            _, timestamp, symbol, action, qty, price, _ = trade
            if action == "BUY":
                buy_queue.append((qty, price))
            elif action == "SELL":
                # Match this sell with previous buys (FIFO)
                remaining_qty = qty
                while remaining_qty > 0 and buy_queue:
                    buy_qty, buy_price = buy_queue[0]
                    if buy_qty <= remaining_qty:
                        # This buy is fully consumed
                        pnl = (price - buy_price) * buy_qty
                        total_pnl += pnl
                        if pnl > 0:
                            winning_trades += 1
                        else:
                            losing_trades += 1
                        remaining_qty -= buy_qty
                        buy_queue.pop(0)
                        round_trips += 1
                    else:
                        # Partially consume this buy
                        pnl = (price - buy_price) * remaining_qty
                        total_pnl += pnl
                        if pnl > 0:
                            winning_trades += 1
                        else:
                            losing_trades += 1
                        buy_queue[0] = (buy_qty - remaining_qty, buy_price)
                        remaining_qty = 0
                        round_trips += 1
                # If there is remaining qty (should not happen if we don't sell more than we bought)
                # but ignore for simplicity
    
    num_trades = winning_trades + losing_trades
    win_rate = (winning_trades / num_trades * 100) if num_trades > 0 else 0.0
    
    return {
        "total_pnl": total_pnl,
        "win_rate": win_rate,
        "num_trades": num_trades,
        "winning_trades": winning_trades,
        "losing_trades": losing_trades,
        "round_trips": round_trips
    }

def generate_report(narrative_prompt, stats):
    """
    Generate a report narrative using the LLM.
    :param narrative_prompt: base prompt for the model
    :param stats: dictionary of computed statistics
    :return: narrative string
    """
    # Prepare the prompt with the stats (but the numbers are not generated by the model)
    prompt = f"""
{narrative_prompt}

Here are the statistics for the trading period:
- Total P&L: ${stats['total_pnl']:.2f}
- Win Rate: {stats['win_rate']:.2f}%
- Number of round-trip trades: {stats['round_trips']}
- Winning trades: {stats['winning_trades']}
- Losing trades: {stats['losing_trades']}

Please write a short, professional summary of the trading performance based on these numbers.
"""
    try:
        model_client = ModelClient()
        narrative = model_client.generate_text(prompt, max_tokens=500, temperature=0.7)
        return narrative
    except ModelError as e:
        # Fallback: if model fails, return a simple template
        return f"""Trading Report:
- Total P&L: ${stats['total_pnl']:.2f}
- Win Rate: {stats['win_rate']:.2f}%
- Number of round-trip trades: {stats['round_trips']}
- Winning trades: {stats['winning_trades']}
- Losing trades: {stats['losing_trades']}

Note: The narrative generation failed due to: {e}
"""

def account_snapshot():
    """
    Fetch account equity and open positions from Alpaca paper (pure Python, no LLM).
    Returns a formatted string section for the daily report.
    """
    try:
        from bot.config import config
        from bot.broker import AlpacaBroker
        broker = AlpacaBroker(config.alpaca_api_key_id, config.alpaca_api_secret_key)
        acct = broker.trading_client.get_account()
        lines = [
            "Account Snapshot (Alpaca paper):",
            f"- Equity: ${float(acct.equity):,.2f}",
            f"- Cash: ${float(acct.cash):,.2f}",
        ]
        positions = list(broker.trading_client.get_all_positions())
        if positions:
            lines.append(f"- Open positions: {len(positions)}")
            for p in positions:
                lines.append(
                    f"  * {p.symbol}: {float(p.qty):.6f} @ ${float(p.avg_entry_price):,.2f} "
                    f"(unrealized P&L: ${float(p.unrealized_pl):,.2f})"
                )
        else:
            lines.append("- Open positions: none (flat)")
        return "\n".join(lines)
    except Exception as e:
        return f"Account snapshot unavailable: {e}"

def shadow_snapshot():
    """Shadow account section for the daily report (virtual $20 ledger)."""
    try:
        from bot.config import config
        from bot.broker import AlpacaBroker
        from bot.shadow import ShadowAccount
        broker = AlpacaBroker(config.alpaca_api_key_id, config.alpaca_api_secret_key)
        shadow = ShadowAccount(config, broker)
        lines = [f"AI Shadow Account (virtual ${shadow.start_cash:.0f}):",
                 f"- {shadow.status_line()}",
                 f"- Realized P&L from closed AI trades: ${shadow.realized_pnl():.2f}"]
        return "\n".join(lines)
    except Exception as e:
        return f"Shadow account snapshot unavailable: {e}"


def create_daily_report():
    """
    Create a daily report by reading trades from journal, computing stats,
    and generating a narrative.
    """
    journal = TradeJournal()
    # Get all trades (or maybe only today's trades? For simplicity, get all)
    trades = journal.get_trades()
    if not trades:
        return f"""=== Trading Bot Daily Report ===
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{account_snapshot()}

{shadow_snapshot()}

Statistics:
- Total P&L: $0.00
- Win Rate: 0.00%
- Number of round-trip trades: 0
- Winning trades: 0
- Losing trades: 0

Narrative:
No trades have been executed yet. The bot is monitoring BTC/USD, ETH/USD, and SOL/USD
for SMA20/SMA50 crossovers and will act on the first signal.
"""
    
    stats = compute_pnl_and_winrate(trades)
    
    # Base prompt for the narrative
    base_prompt = "You are a trading assistant. Write a concise daily report summarizing the performance of a crypto trading bot."
    
    narrative = generate_report(base_prompt, stats)
    
    # Combine stats and narrative into a report
    report = f"""
=== Trading Bot Daily Report ===
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{account_snapshot()}

{shadow_snapshot()}

Statistics:
- Total P&L: ${stats['total_pnl']:.2f}
- Win Rate: {stats['win_rate']:.2f}%
- Number of round-trip trades: {stats['round_trips']}
- Winning trades: {stats['winning_trades']}
- Losing trades: {stats['losing_trades']}

Narrative:
{narrative}
"""
    return report.strip()